HEPAddr         = "0.0.0.0:9060"
HEPWorkers      = 100
MQName          = ""
MQAddr          = ""
MQTopic         = ""
PromAddr        = ""
PromTargetIP     = ""
PromTargetName   = ""
DBDriver        = "mysql"
DBAddr          = "localhost:3306"
DBBulk          = 100
DBName          = "homer_data"
DBUser          = "test"
DBPass          = "test"
AlegID          = "x-cid"
LogDbg          = ""
LogLvl          = "info"
LogStd          = false

# Examples:
# -------------------------------------
# PromAddr        = "0.0.0.0:9999"
# PromTargetIP     = "10.1.2.3,10.1.2.4"
# PromTargetName   = "asterisk,sbc"
# LogDbg          = "hep,sql"
# LogLvl          = "warning"
