HEPAddr         = "0.0.0.0:9060"
HEPWorkers      = 100
MQName          = ""
MQAddr          = ""
MQTopic         = ""
PromAddr        = ""
PromTargetIP    = ""
PromTargetName  = ""
DBDriver        = "mysql"
DBAddr          = "localhost:3306"
DBBulk          = 100
DBName          = "homer_data"
DBUser          = "test"
DBPass          = "test"
AlegID          = "x-cid"
LogDbg          = ""
LogLvl          = "info"
LogStd          = false

# Examples:
# -------------------------------------
# PromAddr        = "0.0.0.0:8899"
# PromTargetIP    = "10.1.2.3,10.1.2.4,10.1.2.5,10.1.2.6,10.1.2.7"
# PromTargetName  = "sbc_access,sbc_core,kamailio,asterisk,pstn_gateway"
# LogDbg          = "hep,sql"
# LogLvl          = "warning"
