version: '3.1'
services :
  db:
    image: mysql:8
    environment:
      #MYSQL_ROOT_PASSWORD: toor
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
  admin:
    image: adminer
    depends_on: 
      - db
    ports:
      - 8080:8080

